users:
  - default
  - name: vmadmin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAXPsVf7QLyG32wyD6Czun0hBps/1urYxu15RiNgdT2w donotuse@example.com 
