---
- name: A simple playbook
  hosts: ansible_hosts
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Output some information on our host
      ansible.builtin.debug:
        msg: I am connecting to {{ ansible_facts['nodename'] }} which is running {{
          ansible_facts['distribution'] }} {{
          ansible_facts['distribution_version'] }}
